# Generated by Django 5.2.4 on 2025-08-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_post_created_at_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='media/images'),
        ),
    ]
