# Generated by Django 5.2.4 on 2025-08-02 16:51

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bangla', 'bangla'), ('english', 'english'), ('hindi', 'hindi'), ('urdho', 'urdho')], default='bangla', max_length=200),
        ),
    ]
