# Generated by Django 5.2.4 on 2025-08-07 15:27

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
