# Generated by Django 5.2.4 on 2025-08-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
